PROJECTNAME:str = 'AlliedWare'
PROJECT_TITLE:str = f"{PROJECTNAME:^14}\nPDFs"

WINDOWWEIGHT:int = 800
WINDOWHEIGHT:int = 700
WINDOWSIZE:str = f'{WINDOWWEIGHT}x{WINDOWHEIGHT}'

APPEARANCE_MODE:str = 'dark'
COLOR_THEME:str = 'dark-blue'


